export const CardsData = [
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Software Engineering',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Data Science',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Cyber Security',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Product Management',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Data Science',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Data Science',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'Data Science',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'UI/UX Design',
  },
  {
    foto: '/Testimony/VazhaK.jpg',
    nama: 'Paja Kari India',
    posisi: 'HR',
    jurusan: 'Sistem Informasi 2024',
    bidang: 'UI/UX Design',
  },
]
