on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: ~/deploy.sh frontend ${{ github.ref_name }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
